<?php

namespace SE\GestrecBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IntervenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervenantRepository extends EntityRepository
{
}
